### ISSUE TITLE
how to save unit? 

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/cheminfo-types#12]
as string or as code or both or is unit its own type? 

unit would we its own type, for example, in the SciData schema https://stuchalk.github.io/scidata/contexts/scidata_unit.jsonld but it is in the quantity type in schema.org

**Comment by kjappelbaum** [comment]
schema.org allows both https://schema.org/QuantitativeValue

**Comment by kjappelbaum** [comment]
i would favor a `Unit` type such that a specific renderer for units can then deal with these questions. A unit might either have a text or a code. I think most of the other fields in https://stuchalk.github.io/scidata/contexts/scidata_unit.jsonld are not needed.

**Comment by djeanner** [comment]
Keep simplicity in mind. For us, making the first implementation, the temptation to go for the finest and most flexible and complex level of units,description, *etc.* is high. 

But for our pretended followers who will be reading each line of the data to generate similar documents each added level of complexity will open questions marks as how to use the different possible choices. This would impose to document everything very well which is terrible time consuming which is also assuming that people read - which is not the case. 

So, for internal use, sure, use (data format for work) use the most complex needed, but for the metadata or key-parameter/data that are supposed to be the ground for a common bases of chemistry meta/data we should keep it simple. 

Possible problem, if we start using different units, a visualizer or converter may need all kings of processing to make conversion. Solution: use a fancy unit, but, in parallel, a simple key:value, for example TempK: 203.0

**Comment by kjappelbaum** [comment]
with @lpatiny we discussed that we won't have two fields for unit text/code but only one field that might store both to allow for the case that someone needs "strange" units.
