### ISSUE TITLE
do we want to have subtypes for positive/negative etc. value

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/cheminfo-types#16]
to enforce constraints.
or is this too many types in the end

**Comment by kjappelbaum** [comment]
i think we should at maximum have one for enforcing positivity atm. 
one problem i see, for example, is for ranges. Do we want to have all combinations of constraints that there might be for ranges as types, i think no. 

maybe I would maybe not even have this that down level but rather have type specific validators.

**Comment by lpatiny** [comment]
There is no way to enforce in typescript. We would need to have the original files in JSON schema.

**Comment by kjappelbaum** [comment]
>There is no way to enforce in typescript. We would need to have the original files in JSON schema. 

the extension we do does this with `@maximum` and `@minimum` and we're using this at the moment. But since it is hard to enforce with the types directly i think we should not use this at the moment.

**Comment by kjappelbaum** [comment]
I think the conclusion was that we do not want to go down this route as TS does not allow us to do this easily.
