### ISSUE TITLE
BP or BoilingPoint ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo-types#19]
Should we use abbreviation or the full name ?

**Comment by kjappelbaum** [comment]
I favor using the full name as we usually have autocomplete, so writing out the name is not an issue and it makes the code easier to understand for outsiders 

the downside of long names is that they might make code unnecessarily long but personally i feel the first point is more important, in particular for something like a schema

**Comment by kjappelbaum** [comment]
Actually, i would as closely follow the full naming that is used in CHMO or the gold book. For example, there was in the past some stuff that was named "infrared" whereas others had the explicit mention of "spectroscopy"

**Comment by lpatiny** [comment]
We all agree not to use abbreviation.
