### ISSUE TITLE
No siValue ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo-types#21]
Could we decide that we don't calculate the siValue and that this is something that the database should take into account when saving the value ?

```js
export interface QuantitytWithUnit {
  value: number;
  unitText: string; 
  unitCode: string|URL; 
  siValue: number; // To be removed
}
```

**Comment by kjappelbaum** [comment]
i would be in favor of this as this is redundant and i did not see it in other schemas

**Comment by kjappelbaum** [comment]
i dropped it now

**Comment by lpatiny** [comment]
Ok
