### ISSUE TITLE
QuantitytWithUnit and RangeWithUnit

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo-types#22]
Should we rather go for:
```js
export interface QuantityWithUnit {
  value: number;
  unitText: string; 
  unitCode: string|URL; 
  minValue: number;
  maxValue: number;
}
```
or rather

```js
export interface QuantityWithUnit {
  value: number;
  unitText: string; 
  unitCode: string|URL; 
}
export interface RangeWithUnit {
  minValue: number;
  maxValue: number;
  unitText: string; 
  unitCode: string|URL; 
}
```

Thinking about a boiling point we would then have
```js
export type BP {
  temperature: ValueWithUnit|RangeWithUnit,
  pressure: ValueWithUnit|RangeWithUnit,
}
```

**Comment by kjappelbaum** [comment]
or 

```
export interface QuantityWithUnit {
  value: number | NumberWithUncertainty;
  unitText: string; 
  unitCode: string|URL; 
}
```

**Comment by kjappelbaum** [comment]
I think there are several points here: 
- it is currently not super clear for outsiders what the difference between range and uncertainty is
- these value/range components/types might also need to be able to deal with uncertainty (which might also come in different forms) 
- if we have min/max and quantity in the same type we need to have a kind of ugly conditional optionality (https://stackoverflow.com/questions/49524414/typescript-interface-conditional-optional-parameters). This is, enforce that either min and max or the value are there

**Comment by lpatiny** [comment]
```js
export interface Unit {
  unitText: string; 
  unitCode: string;  
}
export interface QuantityWithUnit extends Unit {
  value: number;
}
export interface RangeWithUnit extends Unit {
  minValue: number;
  maxValue: number;
}
type ValueWithUnit = QuantityWithUnit | RangeWithUnit;
```

Thinking about a boiling point we would then have
```js
export type BoilingPoint = {
  temperature: ValueWithUnit,
  pressure: ValueWithUnit,
}
```

**Comment by kjappelbaum** [comment]
this gets a bit more complicated when one wants to allow for uncertainty, doesn't it? Because then one would somehow assume that the standard deviation, for example, is the same for both ends. But I would be fine with that.
