### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/cheminfo-types#30]
to "cheminfo types"?

**Comment by kjappelbaum** [comment]
any preference @lpatiny

**Comment by djeanner** [comment]
I would argue that you need not one set (which could by type) but (at least) two.
- a type for files (say a .sdf file), a Bruker 1D spectrum (1r, procs, acqus,...) a Gaussian geometry optimization file.
- a type for objects (a chemical structure, a spectrum)

Indeed, one file may contain multiplet objects with different flavors. 
Each (existing) parser will correspond to a type of file.
The structure, spectra objects should have their own definition, mapping the data from the output of the files.

This image was designed in a different context, but shows the two steps: 
left: Parse a **file type** (Bruker spectrum)
middle: create an **object type** (1D 1H spectrum) 
right: mapping to official "IUPAC" objects was a proposition I made but it is abandonned.
<img width="757" alt="Screenshot 2021-05-18 at 12 51 25 " src="https://user-images.githubusercontent.com/26463431/118639311-0cc52e00-b7d8-11eb-9f82-46860b90e92a.png">


Very crude/exploratory list of object type:

<img width="765" alt="Screenshot 2021-05-18 at 12 52 04 " src="https://user-images.githubusercontent.com/26463431/118639255-fcad4e80-b7d7-11eb-8e25-026b0c7f4547.png">

General problem we try to solve: 



<img width="582" alt="Screenshot 2021-05-18 at 12 52 24 " src="https://user-images.githubusercontent.com/26463431/118639252-fa4af480-b7d7-11eb-8519-ab7364468696.png">

**Comment by kjappelbaum** [comment]
Thanks, I think this repo is mainly for the (abstract) typescript types, that can then be imported by other packages and the derived json-schema/ld. 

For the implementation on the parser level there are the parser repos.

**Comment by lpatiny** [comment]
Rename the repo looks good to me.

**Comment by kjappelbaum** [comment]
renamed the repo and the comment from @djeanner is also in #36
