### ISSUE TITLE
About how we store quantities entered by users

### ISSUE THREAD

**Issue by targos** [cheminfo/cheminfo-types#48]
@kjappelbaum

I thought this week about something that seems important. I'm opening this issue after discussing with @lpatiny.
In the current design, fields that hold quantitative values are defined with the [`number` type](https://github.com/cheminfo/cheminfo-types/blob/e4bd7ebcdf10e9b3a973f7661dfba36e9580d584/src/general/QuantitativeValue.ts#L6). This makes absolute sense in theory, but I'd like to discuss about the possibility to use strings instead.
The mean reason is that it is not possible to store significant zeroes in a number: if a user enters "1.00 mg", as a number it's exactly the same as "1 mg".
Also, I haven't looked into it, but there may be reasonable numbers that cannot be represented as a 64-bit floating point number, and would therefore be rounded up or down to the closest value, losing precision.

Thoughts?

**Comment by kjappelbaum** [comment]
good point, one way other data models, e.g., scidata, follow is to have a field for the significant digits (e.g., 
 https://stuchalk.github.io/scidata/contexts/scidata_value.jsonld). 

>Also, I haven't looked into it, but there may be reasonable numbers that cannot be represented as a 64-bit floating point number, and would therefore be rounded up or down to the closest value, losing precision.

I'm not aware of any example (of experimental data) where this is the case but if we come up with an example where this is indeed an issue we should consider the string. 

the advantage of having the string compared to the the significant digits field would be that we do not have split the information across two fields. The disadvantage is that we somehow store the quantitative value in an "unnatural" form and one would always need to cast it to a number before doing anything with it.

**Comment by targos** [comment]
Using a separate field with the number of significant digits SGTM. We will probably have to write a library to parse the values because js-quantities doesn't extract this information.
I think that in the database we will keep the original raw value as entered by the user (to not lose it in case of conversion errors).
